"""tables init

Revision ID: 2fb6c439db89
Revises: 
Create Date: 2025-03-30 17:22:44.279679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fb6c439db89'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Category',
    sa.Column('Category_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Category_Name', sa.String(length=100), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('Category_ID')
    )
    op.create_table('User',
    sa.Column('User_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('User_ID'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('Document',
    sa.Column('Document_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Category_ID', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=100), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('Default_Content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['Category_ID'], ['Category.Category_ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Document_ID')
    )
    op.create_table('Modified_Document',
    sa.Column('Modification_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('User_ID', sa.Integer(), nullable=False),
    sa.Column('Document_ID', sa.Integer(), nullable=False),
    sa.Column('Modified_Content', sa.Text(), nullable=False),
    sa.Column('Modification_Date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('Payment_Status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['Document_ID'], ['Document.Document_ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['User_ID'], ['User.User_ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Modification_ID')
    )
    op.create_table('Payment',
    sa.Column('Payment_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Modification_ID', sa.Integer(), nullable=False),
    sa.Column('Amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('Payment_Date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('Payment_Method', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['Modification_ID'], ['Modified_Document.Modification_ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Payment_ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Payment')
    op.drop_table('Modified_Document')
    op.drop_table('Document')
    op.drop_table('User')
    op.drop_table('Category')
    # ### end Alembic commands ###
